In [19]:
import torch
import numpy as np
import numba as nb
import cupy as cp
from sympy import *
from sympy.physics.quantum import TensorProduct

In [20]:
X = [[0.,1.], [1.,0.]]
Y = [[0.,-1j], [1j,0.]]
x1 = [4, 1.]
x2 = [1.,5.]

In [21]:
t1 = torch.tensor(x1, device='cuda')
t2 = torch.tensor(x2, device='cuda')
torch.tensordot(t1, t2, dims=0)

tensor([[ 4., 20.],
        [ 1.,  5.]], device='cuda:0')

In [22]:
q1 = Matrix(x1)
q2 = Matrix(x2)

In [23]:
TensorProduct(q1,q2.transpose())

Matrix([
[4.0, 20.0],
[1.0,  5.0]])

In [24]:
n1 = np.array(X)
n2 = np.array(Y)
np.tensordot(n1, n2, axes=0)

array([[[[0.+0.j, 0.-0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 0.-1.j],
         [0.+1.j, 0.+0.j]]],


       [[[0.+0.j, 0.-1.j],
         [0.+1.j, 0.+0.j]],

        [[0.+0.j, 0.-0.j],
         [0.+0.j, 0.+0.j]]]])

In [25]:
n1 = cp.array(X)
n2 = cp.array(Y)
cp.tensordot(n1, n2, axes=0)

array([[[[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]],

        [[0.+0.j, 0.-1.j],
         [0.+1.j, 0.+0.j]]],


       [[[0.+0.j, 0.-1.j],
         [0.+1.j, 0.+0.j]],

        [[0.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]]]])

In [90]:
ket0 = cp.array([1., 0.])
ID = cp.array([[1, 0], [0, 1]]) 
X = cp.array([[0, 1], [1, 0]])
H = cp.array([[1, 1], [1, -1]])
q1 = ket0
q2 = ket0
q3 = ket0
q = cp.kron(q1, q2)
#q = cp.tensordot(q, q3, axes=0)

U = cp.kron(ID, X)
#U = cp.tensordot(U, ID, axes=0)

In [91]:
#U=U.reshape((8, 8))

In [92]:
#q=q.reshape((8, 1))

In [93]:
U

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [94]:
q=q.reshape((4,1))

In [95]:
U*q

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
cp.kron(cp.kron(ID,X),ID)

array([[0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])