In [13]:
import numpy as np
import numba as nb
import cupy as cp
from sympy import *
from sympy.physics.quantum import TensorProduct
import time
from cmath import *

In [2]:
X = [[0.,1.], [1.,0.]]
Y = [[0.,-1j], [1j,0.]]
x1 = [4, 1.]
x2 = [1.,5.]

In [3]:
q1 = Matrix(x1)
q2 = Matrix(x2)

In [4]:
TensorProduct(q1,q2.transpose())

Matrix([
[4.0, 20.0],
[1.0,  5.0]])

In [5]:
ket0 = cp.array([1., 0.])
ID = cp.array([[1, 0], [0, 1]]) 
X = cp.array([[0, 1], [1, 0]])
H = cp.array([[1, 1], [1, -1]])
q1 = ket0
q2 = ket0
q3 = ket0
q = cp.kron(q1, q2)
#q = cp.tensordot(q, q3, axes=0)

U = cp.kron(X, X)
#U = cp.tensordot(U, ID, axes=0)

In [6]:
U

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [7]:
q=q.reshape((4,1))
q

array([[1.],
       [0.],
       [0.],
       [0.]])

In [8]:
cp.dot(U,q)

array([[0.],
       [0.],
       [0.],
       [1.]])

In [9]:
t0 = time.time()
a1 = np.random.rand(120,120)
a2 = np.random.rand(120,120)
a3 = np.kron(a1,a2)
print(str(time.time()-t0)+"s")

5.232177257537842s


In [10]:
t0 = time.time()
a1 = cp.random.rand(120,120)
a2 = cp.random.rand(120,120)
a3 = cp.kron(a1,a2)
print(str(time.time()-t0)+"s")

0.21177291870117188s


In [12]:
2*H

array([[ 2,  2],
       [ 2, -2]])

In [15]:
def Matrix1(Input):
    if(True):
        M = cp.array(Input)
    else:
        M = sympy.Matrix([[1, 0], [0, 0]])  # |0><0|
    return M

In [16]:
M = 1 / sqrt(2) * Matrix1([[1, 1], [1, -1]])

In [17]:
M

array([[ 0.70710678+0.j,  0.70710678+0.j],
       [ 0.70710678+0.j, -0.70710678+0.j]])